name: Polaris SCR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  scr:
    uses: cyberhulk99/polaris-workflows/.github/workflows/polaris-scr.yml@main
    with:
      app_key: subfuzz
      polaris_url: https://mom-walter-revenues-rugs.trycloudflare.com
      rules_repo_owner: cyberhulk99
